### ISSUE TITLE
The option for running the script in a VM instance with no web browser

### ISSUE THREAD

**Issue by marilur** [GoogleCloudPlatform/compute-getting-started-python#2]
The code seems a bit old. I tried to run it on a VM in GCE where there's no web browser, since it's only the terminal interface. 

It will be good to update the code to be able to run. I made the changes like this to the main.py file (taken from other code examples):

import logging
import sys
import argparse
import httplib2
from oauth2client.client import flow_from_clientsecrets
from oauth2client.file import Storage
from oauth2client import tools
from oauth2client.tools import run_flow
from apiclient.discovery import build
import json
import gce

IMAGE_URL = 'http://storage.googleapis.com/gce-demo-input/photo.jpg'
IMAGE_TEXT = 'Ready for dessert?'
INSTANCE_NAME = 'startup-script-demo6'
DISK_NAME = INSTANCE_NAME + '-disk'
INSERT_ERROR = 'Error inserting %(name)s.'
DELETE_ERROR = """
Error deleting %(name)s. %(name)s might still exist; You can use
the console (http://cloud.google.com/console) to delete %(name)s.
"""

def delete_resource(delete_method, *args):
  """Delete a Compute Engine resource using the supplied method and args.

  Args:
    delete_method: The gce.Gce method for deleting the resource.
  """

  resource_name = args[0]
  logging.info('Deleting %s' % resource_name)

  try:
    delete_method(*args)
  except (gce.ApiError, gce.ApiOperationError, ValueError) as e:
    logging.error(DELETE_ERROR, {'name': resource_name})
    logging.error(e)

  # Load the settings for this sample app.
  #settings = json.loads(open(gce.SETTINGS_FILE, 'r').read())

def main(argv):
  # Load the settings for this sample app.
  settings = json.loads(open(gce.SETTINGS_FILE, 'r').read())

  logging.basicConfig(level=logging.INFO)

  parser = argparse.ArgumentParser(
    description=__doc__,
    formatter_class=argparse.RawDescriptionHelpFormatter,
    parents=[tools.argparser])

  # Parse the command-line flags.
  flags = parser.parse_args(argv[1:])

  # Perform OAuth 2.0 authorization.
  #flow = flow_from_clientsecrets(CLIENT_SECRETS, scope=MANAGE_SCOPE)
  #storage = Storage(OAUTH2_STORAGE)
  flow = flow_from_clientsecrets(
      settings['client_secrets'], scope=settings['compute_scope'])
  storage = Storage(settings['oauth_storage'])
  credentials = storage.get()

  if credentials is None or credentials.invalid:
    credentials = run_flow(flow, storage, flags)
  http = httplib2.Http()
  auth_http = credentials.authorize(http=http)

..... the rest of the code rest instact

**Comment by jonparrott** [comment]
This should no longer be an issue as we no longer use the web flow to get credentials, please let me know if it is and I'll re-open.
