### ISSUE TITLE
Document Use of Tags

### ISSUE THREAD

**Issue by pnovotnak** [GoogleCloudPlatform/compute-getting-started-python#8]
Document creation of instances with tags

**Comment by jonparrott** [comment]
This example is designed to be as minimal as possible. Adding tags to the call to ``compute.instances().insert`` should only require you to modify the ``config`` dictionary:

```python
    config = {
        'name': name,
        'machineType': machine_type,

        'tags': {
            'items': ['this-is-a-tag']
        },

        ...
    }
```
